[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.1.40",
    "dotenv>=0.9.9",
    "langchain>=0.3.22",
    "ruff>=0.11.2",
]
